import "./globals.css";
import { Inter } from "next/font/google";
import LoginModal from "@/components/Modal/LoginModal";
import RegisterModal from "@/components/Modal/RegisterModal";
import getCurrentUser from "../components/actions/getCurrentUser";
import ToasterProvider from "@/providers/ToasterProvider";
import AdminModal from "@/components/Modal/AdminModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <link
        rel="icon"
        href="./logo.svg"
        type="image/gif"
        sizes="16x16"
      />
      <body className={inter.className}>
        <LoginModal />
        <RegisterModal />
        <div>{children}</div>
        <ToasterProvider />
      </body>
    </html>
  );
};

export default RootLayout;
